### ISSUE TITLE
Potential name confusion

### ISSUE THREAD

**Issue by ploeh** [jcteague/autofixturejs#1]
Hi

Please accept my apologies if you consider this a misuse of a GitHub issue.

I came across this project today because I have a search agent set up to watch for the name _AutoFixture_, and just wanted to drop you a line... Please read on, this isn't a _cease and desist_ letter - just a friendly note that the name may confuse some users...

The reason I have a search agent looking for the name _AutoFixture_ is that I'm the inventor and [Benevolent Dictator](http://oss-watch.ac.uk/resources/benevolentdictatorgovernancemodel) of a fairly successful open source project called [AutoFixture](https://github.com/AutoFixture/AutoFixture).

Now, you are entirely free to use the name AutoFixture for a Javascript implementation - you probably arrived at the name the same way that I did. However, I just wanted to point you to the existing AutoFixture project, because it may be a potential source of confusion to users.

Obviously, node programmers are likely to be blissfully unaware of the .NET AutoFixture project, but people with prior experience with AutoFixture for .NET may be confused if autofixturejs uses completely different concepts, etc.

Additionally, it may make it difficult to search for AutoFixture documentation, etc. The reason I'm writing is that this has the potential to confuse both AutoFixture .NET users, as well as autofixturejs users.

Perhaps we could deal with such potential issues in one of the following ways:
- Align the concepts and names etc. between the two projects. A couple of years ago, @moodmosaic expressed an interest in creating a port of AutoFixture to Javascript, and although I don't currently have the bandwidth to pour a lot of hours into this, I'd certainly be interested in using it myself. Perhaps we could even make autofixturejs part of the [AutoFixture GitHub organisation](https://github.com/AutoFixture).
- Perhaps find another name for this Javascript project.

You are completely free to ignore this message, and keep working on your project. My motivation for writing to you is only that, based on the ReadMe for this project, it looks like you're unaware of the existing AutoFixture project, and I just wanted to point out to you that prior art exists, and that it may confuse your potential users.

**Comment by moodmosaic** [comment]
[AutoFixture](https://github.com/AutoFixture/AutoFixture) has been around at least since Jan 29, 2010 and nowadays seems to be also [known to Node.js users](https://github.com/bbyars/mountebank/issues/14#issuecomment-42748897). A few days ago there was also a [question on Twitter](https://twitter.com/lensbjerg/status/464404453874216960) about AutoFixture in JavaScript.

@ploeh wrote:

> Align the concepts and names etc. between the two projects.

IMHO, this is a great idea but also fairly big task.

It could be a lot easier if we first create a new JavaScript project in the [AutoFixture GitHub organisation](https://github.com/AutoFixture), set the foundations for the public JavaScript API and then try to re-use the existing functionality of this project – if possible.

That's primarily because [AutoFixture](https://github.com/AutoFixture/AutoFixture) is not exactly a random data generator. It encapsulates concepts from the [xUnit Test Patterns](http://www.amazon.com/xUnit-Test-Patterns-Refactoring-Code/dp/0131495054) book by Gerard Meszaros e.g. [Equivalence Sets](http://xunitpatterns.com/equivalence%20class.html), deriving values drained from the aforementioned Sets generalized by the [80–20 rule](http://en.wikipedia.org/wiki/Pareto_principle), Custom Assertions, and more.

At the moment, I believe, and suggest friendly, that the easiest decision that will probably result to less confusion for the [AutoFixture](https://github.com/AutoFixture/AutoFixture) users, and this project's potential users, would be to find another name for this project.

**Comment by jcteague** [comment]
My appologies, I never received notice about this issue (something I'll see if I can remedy)

I'm familiar with Autofixture.  I have no problems changing the name, but it's one of those things I and not very good at.  Suggestions welcome.

**Comment by TheEvilDev** [comment]
I'm very interested in this project. I discovered it while searching for AutoFixture Javascript in the context of knowing about the .NET project (and loving it), and wanting something similar for js. While I understand AutoFixture.NET is much more than a data generator, for me, this was the core feature I need more than anything, and this project seems to fit that bill, and was easy to discover because of it's name.

If you could align the concepts and goals of the projects, that would be the ultimate. I can understand the concern over potential confusion for people working across the platforms, but I don't think this project is that far off the mark that if discovered by accident. Just my thoughts.

Look forward to playing with this library! Is there plans to release it on NPM?

**Comment by jcteague** [comment]
@TheEvilDev It is available on npm, but it might be a little out of date.  I'm working on a node app again, so I'm sure there will be some activity here in the coming weeks.

**Comment by kalebpederson** [comment]
Quite a while ago I looked for a version of AutoFixture for JavaScript and didn't find anything. Since nothing existed at that time, including this project, I wrote one that I wasn't permitted by work to Open Source at the time. My employer recently decided to allow us to open source certain things and so my implementation  is now [available on GitHub](https://github.com/NextITCorp/AutoFixture.js/blob/master/AutoFixtureSpec.js).

When designing it I purposefully made it very much like the C# implementation so it would be easier to learn, which you can see from the associated tests linked to above. Right now the API is quite similar but the backend is a bit different, in that I'm not keeping track of previous values, the numbers generated are more random, etc.

I'm in the process of cleaning it up, such as making it work with AMD, CJS, publishing to NPM, etc., but I'd like to avoid the naming conflict with this project yet still make it easy to find for individuals familiar with Mark's AutoFixture.

@ploeh and @jcteague, do you have suggestions on what you'd like to see happen? I have no objections to integrating into the AutoFixture organization as I intended it to be as similar as possible.

**Comment by jcteague** [comment]
closing issue, since no has I don't have a better name
